services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"     
    init: true
    ports:
      - 80:80 # redirect
      - 443:443